### ISSUE TITLE
Lombok usage

### ISSUE THREAD

**Issue by hohwille** [devonfw-forge/devonfw-microservices#29]
In devon4j we have a long history of discussions about using Lombok or not.
Here it seems we are pushing towards using lombok.
I want to be neutral and open in this regard but I asked some projects using devon4j that switched to Lombok or went away from it for specific reasons about feedback.
In the end I would love to have a solution that neither forces to use Lombok nor prevents to use it and gives the projects freedom of choice.

**Comment by hohwille** [comment]
We have done a poll on this topic with out internal projects using lombok, devon4j, etc.
The feedback is neutral to positive regarding lombok.
So for me the result is:
* We can recommend lombok to save boiler-plate code
* We should still leave the usage rather optional so an alternative is to leave lombok out and write/generate getters, setters and potential equals, hashCode methods that are comitted to VCS (git).

**Comment by GuentherJulian** [comment]
The ticket is closed as it will be continued and documented in a new [issue](https://github.com/devonfw/devon4j/issues/476)  in the devon4j repo
