### ISSUE TITLE
setup github actions for CI

### ISSUE THREAD

**Issue by hohwille** [devonfw-forge/devonfw-microservices#30]
We need CI for PRs so I can see that nothing breaks before I merge and we can ensure required quality.

**Comment by hohwille** [comment]
* https://github.com/devonfw/devon4j/blob/master/.github/workflows/build.yml
* https://github.com/devonfw/devon4j/blob/master/.github/workflows/build-pr.yml

**Comment by SchneiderMalte** [comment]
#31
