### ISSUE TITLE
Integration into the documentation

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw-forge/devonfw-microservices#35]
Move every documentation done in the devonfw-microservices repo to the architecture browser or the docs section of the website.

**Comment by hohwille** [comment]
I have already setup the initial structure of the repo @SchettlerKoehler created:
https://github.com/devonfw/devon4quarkus

So we have CI for `master` branch and for PRs as well as documentation synchronization to wiki for devonfw guide.
Now the `documentation` folder in this new repo can be filled and in case any lib code needs to be written, it also has a new home where to place it.

Sample applications however, should have their own repo in https://github.com/devonfw-sample/

**Comment by hohwille** [comment]
IMHO https://github.com/devonfw/devon4quarkus should only contain quarkus/Java specific stuff.
Generic documentation such as "How do I do a service mesh (with kubernetes and Istio)" or "how do I setup and integrate IAM (with keycloak)" is cross-cutting and therefore relevant for all stacks (Java, C#, Node.js, etc.). If suitable such content can start in the architecture browser.

**Comment by hohwille** [comment]
From our website we should present that we hava different stacks:
* .NET
   * C#
   * Xamarin
* Java
   * Spring-boot
   * quarkus
* Node.js

For the outside-in view via the website we should avoid starting with technical names such as `devon4j` or `devon4net`.

**Comment by SchettlerKoehler** [comment]
There are tasks for that that will be taken up by the "New UI experience" team:
https://github.com/devonfw/devonfw.github.io/issues/159
https://github.com/devonfw/devonfw.github.io/issues/151

**Comment by GuentherJulian** [comment]
I created some new issues in devon4quarkus and in the architecture repository to create the documentations on devon4quarkus and move the documentations created in this repository.

**Comment by hohwille** [comment]
IMHO we can now close this issue here.
