### ISSUE TITLE
Setup macro / business architecture

### ISSUE THREAD

**Issue by maybeec** [devonfw-forge/devonfw-microservices#5]
Create basic macro / enterprise architecture and provide discussion and recommendation on technologies

**Comment by GuentherJulian** [comment]
Closed as we have guides for the [architecture](https://github.com/devonfw/devon4j/blob/master/documentation/architecture.asciidoc), [project structure](https://github.com/devonfw/devon4j/blob/master/documentation/guide-structure-modern.asciidoc) and [recommendations](https://github.com/devonfw/devon4j/blob/master/documentation/quarkus/quarkus-template.asciidoc)
